### ISSUE TITLE
Add a `.clear` method 

### ISSUE THREAD

**Issue by anodynos** [Floofies/console-buffer#2]
It would be great if we could `.clear` the buffer, without outputting anything.
Our use case is for test debug logging, that we want to print only if the tests failed.

**Comment by Floofies** [comment]
Thanks for the suggestion! I have added it in commit 3a5f0d8

**Comment by Floofies** [comment]
I have now published NPM package version 1.1.0 which contains this addition.

**Comment by anodynos** [comment]
Excellent, thanks!
